version: '3.9'

services:
    fuseki:
        image: stain/jena-fuseki
        container_name: fuseki
        ports:
            - "3030:3030"
        environment:
            - ADMIN_PASSWORD=admin
    mysql:
        image: mysql
        container_name: mysql
        restart: always
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: test
            MYSQL_DATABASE: repositorydb
            MYSQL_USER: repo
            MYSQL_PASSWORD: repo
        volumes: 
            - mysql_data:/var/lib/mysql
    adminer:
        image: adminer
        container_name: adminer
        restart: always
        ports:
        - "8080:8080"
        environment:
            ADMINER_DEFAULT_SERVER: mysql 
        depends_on:
        - mysql

volumes:
    mysql_data:
